# Generated by Django 2.2.6 on 2019-10-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustivel', models.CharField(help_text='Insira um combustível', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Talao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talao', models.IntegerField(help_text='Insira um código válido de Talão', unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Disponível para uso'), (1, 'Em uso'), (2, 'Usado')])),
            ],
        ),
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale', models.IntegerField(help_text='Insira um código válido de Vale', unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Indisponível para uso'), (1, 'Disponível'), (2, 'Usado')])),
                ('talao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_gc.Talao')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaVale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField(help_text='Insira o valor deste vale')),
                ('observacao', models.TextField(blank=True, max_length=255, verbose_name='Observações')),
                ('combustivel', models.ForeignKey(help_text='Insira um combustível cadstrado no sistema', on_delete=django.db.models.deletion.PROTECT, to='web_gc.Combustivel')),
                ('vale', models.ForeignKey(help_text='Insira um vale cadastrado no sistema', on_delete=django.db.models.deletion.CASCADE, to='web_gc.Vale')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaTalao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('talao', models.ForeignKey(help_text='Insira um talão cadastrado no sistema', on_delete=django.db.models.deletion.CASCADE, to='web_gc.Talao')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroTalao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('talao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_gc.Talao')),
            ],
        ),
    ]
