# Generated by Django 2.2.7 on 2019-12-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrotalao',
            name='posto',
        ),
    ]
