# Generated by Django 2.2.7 on 2019-11-18 21:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustivel',
            name='combustivel',
            field=models.CharField(help_text='Insira um combustível', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='entregatalao',
            name='user_to',
            field=models.ForeignKey(default=None, help_text='Usuário que irá receber o talão', on_delete=django.db.models.deletion.PROTECT, related_name='talao_user_to', to=settings.AUTH_USER_MODEL, verbose_name='Para'),
        ),
        migrations.AlterField(
            model_name='entregavale',
            name='user_to',
            field=models.ForeignKey(default=None, help_text='Usuário que irá receber o vale combustível', on_delete=django.db.models.deletion.PROTECT, related_name='vale_user_to', to=settings.AUTH_USER_MODEL, verbose_name='Para'),
        ),
        migrations.AlterField(
            model_name='talao',
            name='talao',
            field=models.IntegerField(help_text='Insira um valor válido de talão', unique=True, validators=[django.core.validators.MinValueValidator(100, 'Talão inválido'), django.core.validators.MaxValueValidator(999999, 'Talão inválido')], verbose_name='Talao'),
        ),
    ]
