# Generated by Django 2.2.6 on 2019-10-05 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustivel',
            name='combustivel',
            field=models.CharField(help_text='Insira um combustível', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='talao',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disponível para uso'), (1, 'Em uso'), (2, 'Usado')], default=0),
        ),
        migrations.AlterField(
            model_name='talao',
            name='talao',
            field=models.IntegerField(help_text='Insira um código válido de Talão', unique=True, validators=[django.core.validators.MinLengthValidator(6, 'O talão deve conter 6 (seis) dígitos'), django.core.validators.MaxLengthValidator(6, 'O talão deve conter 6 (seis) dígitos')]),
        ),
        migrations.AlterField(
            model_name='vale',
            name='status',
            field=models.IntegerField(choices=[(0, 'Indisponível para uso'), (1, 'Disponível'), (2, 'Usado')], default=0),
        ),
    ]
