# Generated by Django 2.2.6 on 2019-10-05 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0002_auto_20191005_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talao',
            name='talao',
            field=models.IntegerField(help_text='Insira um código válido de Talão', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6, 'O talão deve conter 6 (seis) dígitos'), django.core.validators.MaxLengthValidator(6, 'O talão deve conter 6 (seis) dígitos')]),
        ),
    ]
