# Generated by Django 2.2.7 on 2019-12-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0003_cadastrotalao_posto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrotalao',
            name='posto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='web_gc.Posto'),
        ),
    ]
