# Generated by Django 2.2.7 on 2019-12-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0004_auto_20191203_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrotalao',
            name='posto',
        ),
        migrations.AddField(
            model_name='entregavale',
            name='posto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vale_posto', to='web_gc.Posto'),
        ),
    ]
