# Generated by Django 2.2.6 on 2019-10-06 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0004_auto_20191005_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talao',
            name='talao',
            field=models.IntegerField(help_text='Insira um código válido de Talão', unique=True, validators=[django.core.validators.MinValueValidator(10000, 'ValueError'), django.core.validators.MaxValueValidator(999999, 'ValueError')]),
        ),
    ]
