# Generated by Django 2.2.6 on 2019-10-06 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0005_auto_20191005_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talao',
            name='talao',
            field=models.IntegerField(help_text='Insira um código válido de Talão', unique=True, validators=[django.core.validators.MinValueValidator(100, 'Talão inválido'), django.core.validators.MaxValueValidator(999999, 'Talão inválido')]),
        ),
        migrations.AlterField(
            model_name='vale',
            name='vale',
            field=models.IntegerField(help_text='Insira um código válido de Vale', unique=True, validators=[django.core.validators.MinValueValidator(10000, 'Vale inválido'), django.core.validators.MaxValueValidator(999999, 'Vale inválido')]),
        ),
    ]
