# Generated by Django 2.2.6 on 2019-10-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0006_auto_20191006_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='talao',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='talao',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disponível para uso'), (1, 'Em uso'), (2, 'Usado')], default=0, editable=False),
        ),
    ]
