# Generated by Django 2.2.6 on 2019-10-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0007_auto_20191028_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talao',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disponível para uso'), (1, 'Em uso'), (2, 'Usado')], default=0),
        ),
    ]
