# Generated by Django 2.2.6 on 2019-10-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0009_entregatalao_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregatalao',
            name='asd',
        ),
    ]
