# Generated by Django 2.2.6 on 2019-10-31 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0010_remove_entregatalao_asd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregavale',
            name='combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_gc.Combustivel'),
        ),
        migrations.AlterField(
            model_name='entregavale',
            name='vale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_gc.Vale'),
        ),
        migrations.AlterField(
            model_name='entregavale',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
