# Generated by Django 2.2.6 on 2019-11-01 19:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0011_auto_20191031_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregavale',
            name='combustivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_gc.Combustivel', verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='vale',
            name='vale',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000, 'Vale inválido'), django.core.validators.MaxValueValidator(999999, 'Vale inválido')]),
        ),
    ]
