# Generated by Django 2.2.6 on 2019-11-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_gc', '0013_auto_20191106_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregatalao',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entregavale',
            name='user',
        ),
        migrations.AddField(
            model_name='entregatalao',
            name='current_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='current_user_talao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregatalao',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='to_user_talao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregavale',
            name='current_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='current_user_vale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregavale',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='to_user_vale', to=settings.AUTH_USER_MODEL),
        ),
    ]
