# Generated by Django 2.2.6 on 2019-11-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0014_auto_20191106_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talao',
            name='data',
        ),
        migrations.AlterField(
            model_name='combustivel',
            name='combustivel',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entregatalao',
            name='talao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_gc.Talao'),
        ),
    ]
