# Generated by Django 2.2.6 on 2019-11-07 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_gc', '0015_auto_20191106_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregatalao',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='entregatalao',
            name='to_user',
        ),
        migrations.AddField(
            model_name='entregatalao',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='talao_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregatalao',
            name='user_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='talao_user_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadastrotalao',
            name='talao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talao_cadastro', to='web_gc.Talao'),
        ),
        migrations.AlterField(
            model_name='entregatalao',
            name='talao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talao_entrega', to='web_gc.Talao'),
        ),
        migrations.AlterField(
            model_name='entregavale',
            name='vale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vale_entrega', to='web_gc.Vale'),
        ),
        migrations.AlterField(
            model_name='vale',
            name='talao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talao_vales', to='web_gc.Talao'),
        ),
    ]
