# Generated by Django 2.2.6 on 2019-11-08 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_gc', '0016_auto_20191107_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregavale',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='entregavale',
            name='to_user',
        ),
        migrations.AddField(
            model_name='entregavale',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='vale_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregavale',
            name='user_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='vale_user_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
