# Generated by Django 2.2.6 on 2019-11-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gc', '0017_auto_20191108_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrotalao',
            name='data',
            field=models.IntegerField(),
        ),
    ]
