# Generated by Django 2.2.7 on 2019-12-06 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de cadastro')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_cadastradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de entrada')),
                ('patrimonio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='patrimonio.Patrimonio')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='entrada_patrimonio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de saída')),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrada_saida', to='patrimonio.PatrimonioEntrada')),
                ('patrimonio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_saida', to='patrimonio.Patrimonio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_saidas', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_retiradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FerramentaSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de saída')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='patrimonio.Ferramenta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FerramentaQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quandidade', models.IntegerField(verbose_name='Quantidade')),
                ('ferramenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quantidade', to='patrimonio.Ferramenta')),
            ],
        ),
        migrations.CreateModel(
            name='FerramentaEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de entrada')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='patrimonio.Ferramenta')),
            ],
        ),
    ]
