# Generated by Django 2.2.7 on 2019-12-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonioentrada',
            name='patrimonio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='patrimonio.Patrimonio'),
        ),
        migrations.AlterField(
            model_name='patrimoniosaida',
            name='patrimonio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_saida', to='patrimonio.Patrimonio'),
        ),
    ]
