# Generated by Django 2.2.7 on 2019-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_auto_20191206_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimonio',
            name='codigo',
        ),
        migrations.AddField(
            model_name='ferramentaentrada',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='ferramentaentrada',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ferramentasaida',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='patrimonioentrada',
            name='codigo',
            field=models.IntegerField(default=0, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='patrimonioentrada',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='patrimonioentrada',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patrimoniosaida',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
    ]
