# Generated by Django 2.2.7 on 2019-12-10 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patrimonio', '0003_auto_20191210_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonios_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
