# Generated by Django 2.2.7 on 2019-12-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_patrimonio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de entrada'),
        ),
    ]
