# Generated by Django 2.2.7 on 2019-12-10 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patrimonio', '0005_patrimonio_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramentaentrada',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_entradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ferramentaquantidade',
            name='quandidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
