# Generated by Django 2.2.7 on 2019-12-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0007_auto_20191210_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramentaentrada',
            name='ferramenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='patrimonio.Ferramenta'),
        ),
        migrations.AlterField(
            model_name='ferramentasaida',
            name='ferramenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='patrimonio.Ferramenta'),
        ),
    ]
