# Generated by Django 2.2.7 on 2019-12-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0008_auto_20191210_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramentaquantidade',
            name='ferramenta',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quantidade', to='patrimonio.Ferramenta'),
        ),
    ]
