# Generated by Django 2.2.7 on 2019-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0009_auto_20191210_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramentaquantidade',
            name='quantidade',
            field=models.IntegerField(default=0, editable=False, verbose_name='Quantidade'),
        ),
    ]
