# Generated by Django 2.2.7 on 2019-12-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0010_auto_20191211_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramentaentrada',
            name='ferramenta',
        ),
        migrations.RemoveField(
            model_name='ferramentaentrada',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ferramentaquantidade',
            name='ferramenta',
        ),
        migrations.RemoveField(
            model_name='ferramentasaida',
            name='ferramenta',
        ),
        migrations.RemoveField(
            model_name='ferramentasaida',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ferramentasaida',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='Ferramenta',
        ),
        migrations.DeleteModel(
            name='FerramentaEntrada',
        ),
        migrations.DeleteModel(
            name='FerramentaQuantidade',
        ),
        migrations.DeleteModel(
            name='FerramentaSaida',
        ),
    ]
