# Generated by Django 3.0.7 on 2021-02-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelaConstratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wfm_id', models.IntegerField(unique=True)),
                ('sistema_ext_id', models.CharField(max_length=20)),
                ('contrato', models.CharField(max_length=15)),
                ('recurso', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=50)),
                ('porta', models.CharField(max_length=50)),
                ('porta_n', models.CharField(max_length=10)),
            ],
        ),
    ]
