# Generated by Django 3.0.7 on 2021-02-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentinelaConstratos',
            new_name='SentinelaContratos',
        ),
    ]
