# Generated by Django 3.0.7 on 2021-02-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0002_auto_20210217_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentinelacontratos',
            name='sinal_olt',
            field=models.CharField(default='-10', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentinelacontratos',
            name='sinal_ont',
            field=models.CharField(default='-10', max_length=10),
            preserve_default=False,
        ),
    ]
