# Generated by Django 3.0.7 on 2021-02-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0003_auto_20210220_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentinelacontratos',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
