# Generated by Django 3.0.7 on 2021-02-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0004_sentinelacontratos_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentinelacontratos',
            name='status_sentinela',
            field=models.BooleanField(default=True),
        ),
    ]
