# Generated by Django 3.0.7 on 2021-02-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinela', '0005_sentinelacontratos_status_sentinela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentinelacontratos',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
