# Generated by Django 2.2.7 on 2019-12-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Fornecedor')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('material', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de saída')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='almoxarifado.Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quandidade', models.IntegerField(verbose_name='Quantidade')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quantidade', to='almoxarifado.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de entrada')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquisicoes', to='almoxarifado.Fornecedor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='almoxarifado.Material')),
            ],
        ),
    ]
