# Generated by Django 2.2.7 on 2019-12-05 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almoxarifado', '0002_material_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'peça'), (1, 'unidade'), (2, 'metro'), (3, 'quilo'), (4, 'jogo')], default=1),
        ),
        migrations.AddField(
            model_name='materialsaida',
            name='user_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='retiradas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialsaida',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
