# Generated by Django 2.2.7 on 2019-12-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_auto_20191216_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'peça(s)'), (1, 'unidade(s)'), (2, 'metro(s)'), (3, 'quilo(s)'), (4, 'jogo(s)')], default=1),
        ),
    ]
