# Generated by Django 2.2.7 on 2019-12-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0011_auto_20191218_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
    ]
