# Generated by Django 2.2.7 on 2019-12-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0012_auto_20191218_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.IntegerField(max_length=14, verbose_name='CNPJ'),
        ),
    ]
