# Generated by Django 2.2.7 on 2019-12-21 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almoxarifado', '0014_auto_20191219_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de cadastro')),
                ('tipo', models.IntegerField(choices=[(0, 'Entrada'), (1, 'Saida')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxaridado_ordens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='materialentrada',
            name='ordem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='almoxarifado_ordem_entrada', to='almoxarifado.Ordem'),
        ),
        migrations.AddField(
            model_name='materialsaida',
            name='ordem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='almoxarifado_ordem_saida', to='almoxarifado.Ordem'),
        ),
    ]
