# Generated by Django 2.2.7 on 2019-12-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0015_auto_20191221_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialentrada',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='materialsaida',
            name='ordem',
        ),
    ]
