# Generated by Django 3.1.7 on 2021-03-30 23:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_referencia', models.DateField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cartao_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_to_name', models.CharField(max_length=255)),
                ('user_to_cpf', models.CharField(max_length=11)),
                ('birthday', models.DateField()),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'O valor mínimo deve ser maior ou igual a R$ 0,00')])),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartao_uploads', to='cartao.upload')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartao_recepcoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_to', 'upload')},
            },
        ),
    ]
