# Generated by Django 3.0.7 on 2020-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8),
        ),
    ]
