# Generated by Django 3.0.7 on 2020-06-10 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cont', '0001_initial'),
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Lista criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cont_lista_saida', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cont_lista_retirada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OntItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_lista_itens', to='lista_saida.OntLista')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_material_listas', to='cont.Ont')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Lista criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lista_saida', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lista_retirada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_itens', to='lista_saida.Lista')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_listas', to='almoxarifado.Material')),
            ],
        ),
        migrations.CreateModel(
            name='DefeitoOntLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Lista criada em')),
                ('fornecedor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cont_defeito_lista_retirada', to='almoxarifado.Fornecedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cont_defeito_lista_saida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefeitoOntItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_defeito_lista_itens', to='lista_saida.DefeitoOntLista')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_defeito_material_listas', to='cont.Ont')),
            ],
        ),
    ]
