# Generated by Django 3.0.7 on 2020-06-10 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0002_ontdefeito_ontdefeitodevolucao_ontdefeitohistorico'),
        ('almoxarifado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lista_saida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefeitoOntLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Lista criada em')),
                ('fornecedor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cont_defeito_lista_retirada', to='almoxarifado.Fornecedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cont_defeito_lista_saida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefeitoOntItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_defeito_lista_itens', to='lista_saida.DefeitoOntLista')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_defeito_material_listas', to='cont.Ont')),
            ],
        ),
    ]
