# Generated by Django 3.0.7 on 2020-09-10 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almoxarifado', '0003_auto_20200716_1417'),
        ('cont', '0006_auto_20200826_1703'),
        ('lista_saida', '0002_defeitoontitem_defeitoontlista'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoOntLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Lista criada em')),
                ('fornecedor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cont_manutencao_lista_retirada', to='almoxarifado.Fornecedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cont_manutencao_lista_saida', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManutencaoOntItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_manutencao_lista_itens', to='lista_saida.DefeitoOntLista')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_manutencao_material_listas', to='cont.Ont')),
            ],
        ),
    ]
