# Generated by Django 3.0.7 on 2020-06-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_saida', '0002_tabelateste2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defeitoontitem',
            name='lista',
        ),
        migrations.RemoveField(
            model_name='defeitoontitem',
            name='material',
        ),
        migrations.RemoveField(
            model_name='defeitoontlista',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='defeitoontlista',
            name='user',
        ),
        migrations.DeleteModel(
            name='TabelaTeste2',
        ),
        migrations.DeleteModel(
            name='DefeitoOntItem',
        ),
        migrations.DeleteModel(
            name='DefeitoOntLista',
        ),
    ]
