# Generated by Django 2.2.7 on 2020-04-08 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0017_auto_20191221_1216'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lista_saida', '0003_auto_20191220_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Lista criada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cont_lista_saida', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cont_lista_retirada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OntItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_lista_itens', to='lista_saida.Lista')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_material_listas', to='almoxarifado.Material')),
            ],
        ),
    ]
