# Generated by Django 2.2.7 on 2020-04-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista_saida', '0005_auto_20200408_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontitem',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_lista_itens', to='lista_saida.OntLista'),
        ),
    ]
