# Generated by Django 3.0.7 on 2020-08-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimoniosaida',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='patrimoniosaida',
            name='patrimonio',
        ),
        migrations.RemoveField(
            model_name='patrimoniosaida',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patrimoniosaida',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='PatrimonioEntrada',
        ),
        migrations.DeleteModel(
            name='PatrimonioSaida',
        ),
    ]
