# Generated by Django 2.2.7 on 2019-12-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonioentrada',
            name='status',
            field=models.IntegerField(choices=[(0, 'Estoque'), (1, 'Campo')], default=0),
        ),
        migrations.AlterField(
            model_name='patrimonioentrada',
            name='codigo',
            field=models.IntegerField(default=0, verbose_name='Código'),
        ),
    ]
