# Generated by Django 2.2.7 on 2019-12-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio1', '0002_auto_20191217_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonioentrada',
            name='status',
            field=models.IntegerField(choices=[(0, 'Estoque'), (1, 'Em uso')], default=0),
        ),
        migrations.AlterField(
            model_name='patrimoniosaida',
            name='entrada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrada_saida', to='patrimonio1.PatrimonioEntrada', verbose_name='Patrimônio'),
        ),
    ]
