# Generated by Django 3.0.7 on 2020-08-24 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patrimonio1', '0002_auto_20200824_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de entrada')),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de saída')),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_entrada_saida', to='patrimonio1.PatrimonioEntrada', verbose_name='Patrimônio')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_saida', to='patrimonio1.Patrimonio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_saidas', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonio_retiradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Estoque'), (1, 'Em uso'), (2, 'Defeito'), (2, 'Manutenção'), (3, 'Inutilizado')], default=0)),
                ('codigo', models.IntegerField(default=0, verbose_name='Código')),
                ('valor', models.FloatField(default=0)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_id', to='patrimonio1.Patrimonio')),
            ],
        ),
        migrations.AddField(
            model_name='patrimonioentrada',
            name='patrimonio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_entrada', to='patrimonio1.PatrimonioId'),
        ),
        migrations.AddField(
            model_name='patrimonioentrada',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user_entrada_patrimonio', to=settings.AUTH_USER_MODEL),
        ),
    ]
