# Generated by Django 3.0.7 on 2020-08-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio1', '0004_auto_20200825_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniosaida',
            name='patrimonio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_saida', to='patrimonio1.PatrimonioId'),
        ),
    ]
