# Generated by Django 3.0.7 on 2020-11-22 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patrimonio1', '0006_auto_20201121_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioEntradaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_historico_entrada', to='patrimonio1.PatrimonioId')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrada_historico_patrimonio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
