# Generated by Django 3.0.7 on 2020-08-25 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ferramenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerramentaFechamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Bom'), (1, 'Descarte'), (2, 'Perda')], default=0)),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de descarte')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramenta_fechamentos', to='ferramenta.Ferramenta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_ferramenta_fechamentos', to=settings.AUTH_USER_MODEL)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_from_ferramenta_fechamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
