# Generated by Django 3.0.7 on 2021-01-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
        ('ferramenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramentasaida',
            name='ordem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saida_ordem_ferramenta', to='patrimonio.Ordem'),
        ),
    ]
