# Generated by Django 3.0.7 on 2020-08-25 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ferramenta', '0003_ferramentafechamento_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerramentaQuantidadeFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, editable=False, verbose_name='Quantidade')),
                ('ferramenta', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quantidade_funcionario', to='ferramenta.Ferramenta')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='ferramentas_carga', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
