# Generated by Django 3.0.7 on 2020-08-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferramenta', '0004_ferramentaquantidadefuncionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramentaquantidadefuncionario',
            name='ferramenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantidade_funcionario', to='ferramenta.Ferramenta'),
        ),
        migrations.AlterField(
            model_name='ferramentaquantidadefuncionario',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
