# Generated by Django 3.0.7 on 2020-12-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
        ('ferramenta', '0005_auto_20200826_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramentasaida',
            name='ordem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saida_ordem_ferramenta', to='patrimonio.Ordem'),
        ),
    ]
