# Generated by Django 3.0.7 on 2020-06-10 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Fornecedor')),
                ('cnpj', models.BigIntegerField(verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('material', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de cadastro')),
                ('tipo', models.IntegerField(choices=[(0, 'peça(s)'), (1, 'unidade(s)'), (2, 'metro(s)'), (3, 'quilo(s)'), (4, 'jogo(s)')], default=1)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='materiais_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de cadastro')),
                ('tipo', models.IntegerField(choices=[(0, 'Entrada'), (1, 'Saida')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxaridado_ordens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de saída')),
                ('observacao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='almoxarifado.Material')),
                ('ordem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='almoxarifado_ordem_saida', to='almoxarifado.Ordem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_saidas', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_retiradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quantidade', to='almoxarifado.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de entrada')),
                ('observacao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquisicoes', to='almoxarifado.Fornecedor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='almoxarifado.Material')),
                ('ordem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='almoxarifado_ordem_entrada', to='almoxarifado.Ordem')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_entradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
