# Generated by Django 3.0.7 on 2020-07-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFornecedorPrazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
                ('dias_uteis', models.BooleanField(default=False)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almoxarifado_fornecedor_prazo', to='almoxarifado.Fornecedor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almoxarifado_material_prazo', to='almoxarifado.Material')),
            ],
        ),
    ]
