# Generated by Django 3.0.7 on 2020-07-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_materialfornecedorprazo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialfornecedorprazo',
            unique_together={('material', 'fornecedor')},
        ),
    ]
