# Generated by Django 3.0.7 on 2020-10-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_auto_20200716_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
