# Generated by Django 2.2.7 on 2019-12-06 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_auto_20191205_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsaida',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_saidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialsaida',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almoxarifado_retiradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
