# Generated by Django 2.2.7 on 2019-12-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_auto_20191206_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
    ]
