# Generated by Django 2.2.7 on 2019-12-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0006_auto_20191217_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentrada',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='materialsaida',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
    ]
