# Generated by Django 2.2.7 on 2019-12-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_materialentrada_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialquantidade',
            old_name='quandidade',
            new_name='quantidade',
        ),
    ]
