# Generated by Django 2.2.7 on 2019-12-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0010_auto_20191218_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialquantidade',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quantidade', to='almoxarifado.Material'),
        ),
    ]
