# Generated by Django 2.2.7 on 2019-12-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0013_auto_20191219_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.BigIntegerField(verbose_name='CNPJ'),
        ),
    ]
