# Generated by Django 2.2.7 on 2019-12-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0016_auto_20191221_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentrada',
            name='ordem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='almoxarifado_ordem_entrada', to='almoxarifado.Ordem'),
        ),
        migrations.AddField(
            model_name='materialsaida',
            name='ordem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='almoxarifado_ordem_saida', to='almoxarifado.Ordem'),
        ),
    ]
