# Generated by Django 2.2.7 on 2019-12-20 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista_saida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lista_retirada', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
