# Generated by Django 2.2.7 on 2020-04-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lista_saida', '0004_ontitem_ontlista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_material_listas', to='cont.Ont'),
        ),
    ]
