# Generated by Django 2.2.7 on 2020-03-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontaplicado',
            name='saida',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aplicado_saida_ont', to='cont.OntSaida'),
        ),
        migrations.AddField(
            model_name='ontsaida',
            name='entrada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saida_entrada_ont', to='cont.OntEntrada'),
        ),
    ]
