# Generated by Django 2.2.7 on 2020-04-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0006_auto_20200405_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontaplicado',
            old_name='serial',
            new_name='ont',
        ),
    ]
