# Generated by Django 2.2.7 on 2020-04-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0008_ontsaida_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontsaida',
            name='ordem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saida_ordem_ont', to='almoxarifado.Ordem'),
        ),
    ]
