# Generated by Django 3.0.7 on 2020-06-09 19:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cont', '0013_ontfefeitohistorico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OntFefeitoHistorico',
            new_name='OntDefeitoHistorico',
        ),
    ]
