# Generated by Django 3.0.7 on 2020-06-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0014_auto_20200609_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontdefeitodevolucao',
            name='defeito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='devolucao_defeito', to='cont.OntDefeito'),
        ),
    ]
