# Generated by Django 3.0.7 on 2020-07-02 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talao',
            name='talao',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1, 'Talão inválido'), django.core.validators.MaxValueValidator(999999, 'Talão inválido')], verbose_name='Talao'),
        ),
    ]
