# Generated by Django 3.1.7 on 2021-06-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talao', '0002_auto_20200702_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregavale',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
