# Generated by Django 3.0.7 on 2020-06-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('cont', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontdefeitodevolucao',
            name='ordem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucao_ordem_ont', to='almoxarifado.Ordem'),
        ),
    ]
