# Generated by Django 3.0.7 on 2020-06-10 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cont', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntDefeito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('ont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defeito_ont', to='cont.Ont')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dfeito_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OntDefeitoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_ont_defeito', to='cont.Ont')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defeito_historico_ont', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OntDefeitoDevolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('defeito', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='devolucao_defeito', to='cont.OntDefeito')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucao_fornecedor', to='almoxarifado.Fornecedor')),
                ('ont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucao_ont', to='cont.Ont')),
                ('ordem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucao_ordem_ont', to='almoxarifado.Ordem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucao_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
