# Generated by Django 2.2.7 on 2020-03-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0002_auto_20200309_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código'),
        ),
    ]
