# Generated by Django 3.0.7 on 2020-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0002_ontdefeito_ontdefeitodevolucao_ontdefeitohistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ont',
            name='status',
            field=models.IntegerField(choices=[(0, 'Estoque'), (1, 'Campo'), (2, 'Aplicada'), (3, 'Defeito'), (4, 'Devolvida'), (4, 'Retirada')], default=0, editable=False),
        ),
    ]
