# Generated by Django 2.2.7 on 2020-03-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0003_auto_20200309_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ont',
            old_name='projeto',
            new_name='secao',
        ),
    ]
