# Generated by Django 3.0.7 on 2020-08-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0003_auto_20200702_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OntEntradaHistorico',
        ),
    ]
