# Generated by Django 3.0.7 on 2020-08-26 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almoxarifado', '0003_auto_20200716_1417'),
        ('cont', '0005_ontentradahistorico1'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntDevolucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OntFechamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Defeito'), (1, 'Manutencao')], default=0, editable=False)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OntManutencaoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ontdefeitodevolucao',
            name='defeito',
        ),
        migrations.RemoveField(
            model_name='ontdefeitodevolucao',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='ontdefeitodevolucao',
            name='ont',
        ),
        migrations.RemoveField(
            model_name='ontdefeitodevolucao',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='ontdefeitodevolucao',
            name='user',
        ),
        migrations.AlterField(
            model_name='ont',
            name='status',
            field=models.IntegerField(choices=[(0, 'Estoque'), (1, 'Campo'), (2, 'Aplicada'), (3, 'Defeito'), (4, 'Devolvida'), (5, 'Retirada manutenção')], default=0, editable=False),
        ),
        migrations.DeleteModel(
            name='OntDefeito',
        ),
        migrations.DeleteModel(
            name='OntDefeitoDevolucao',
        ),
        migrations.AddField(
            model_name='ontmanutencaohistorico',
            name='ont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_ont_manutencao', to='cont.Ont'),
        ),
        migrations.AddField(
            model_name='ontmanutencaohistorico',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencao_historico_ont', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ontfechamento',
            name='ont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamento_ont', to='cont.Ont'),
        ),
        migrations.AddField(
            model_name='ontfechamento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ont_fechamento_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ontdevolucao',
            name='fechamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ont_devolucao', to='cont.OntFechamento'),
        ),
        migrations.AddField(
            model_name='ontdevolucao',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ont_devolucao_fornecedor', to='almoxarifado.Fornecedor'),
        ),
        migrations.AddField(
            model_name='ontdevolucao',
            name='ont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucao_ont', to='cont.Ont'),
        ),
        migrations.AddField(
            model_name='ontdevolucao',
            name='ordem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucao_ordem_ont', to='almoxarifado.Ordem'),
        ),
        migrations.AddField(
            model_name='ontdevolucao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ont_devolucao_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
