# Generated by Django 2.2.7 on 2020-04-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0017_auto_20191221_1216'),
        ('cont', '0007_auto_20200405_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontsaida',
            name='ordem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saida_entrada_ordem', to='almoxarifado.Ordem'),
        ),
    ]
