# Generated by Django 3.0.7 on 2020-06-09 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0017_auto_20191221_1216'),
        ('cont', '0010_auto_20200609_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontdefeitodevolucao',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucao_fornecedor', to='almoxarifado.Fornecedor'),
        ),
    ]
