# Generated by Django 3.0.7 on 2020-06-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0017_auto_20191221_1216'),
        ('cont', '0011_auto_20200609_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontdefeitodevolucao',
            name='ordem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devolucao_ordem_ont', to='almoxarifado.Ordem'),
        ),
    ]
