# Generated by Django 3.0.7 on 2020-06-09 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cont', '0012_ontdefeitodevolucao_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntFefeitoHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_ont_defeito', to='cont.Ont')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defeito_historico_ont', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
