# Generated by Django 3.1.7 on 2021-05-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0002_km_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='km',
            name='km_initial',
            field=models.FloatField(null=True),
        ),
    ]
