# Generated by Django 3.1.7 on 2021-05-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0003_auto_20210512_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='km',
            name='km_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='km',
            name='km_initial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
