# Generated by Django 3.1.7 on 2021-05-13 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0004_auto_20210512_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='km',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
